#!/bin/bash
blue='\e[0;34'
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

echo -e "$red

░██████╗░██████╗██╗░░██╗  ██████╗░░█████╗░███╗░░██╗░██████╗░███████╗  ██╗██████╗░
██╔════╝██╔════╝██║░░██║  ██╔══██╗██╔══██╗████╗░██║██╔════╝░██╔════╝  ██║██╔══██╗
╚█████╗░╚█████╗░███████║  ██████╔╝███████║██╔██╗██║██║░░██╗░█████╗░░  ██║██████╔╝$white
░╚═══██╗░╚═══██╗██╔══██║  ██╔══██╗██╔══██║██║╚████║██║░░╚██╗██╔══╝░░  ██║██╔═══╝░
██████╔╝██████╔╝██║░░██║  ██║░░██║██║░░██║██║░╚███║╚██████╔╝███████╗  ██║██║░░░░░
╚═════╝░╚═════╝░╚═╝░░╚═╝  ╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝░╚═════╝░╚══════╝  ╚═╝╚═╝░░░░░
"
echo "=================================================================================="
echo -e "$yellow This Script is for educationnal purposes only. 
 Malicious usage of this Script will not hold the author responsible. 
 Do not pentest without explicit permissions.$white
$cyan CopyRight By Satorugojo@2024$white"
echo "==================================================================================
"

read -p "Victim IP (e.g., 192.168.1): " ip

for i in $(seq 1 255); do
    if nc -v -n -z -w 1 "$ip.$i" 22 2>&1 | grep -q "succeeded"; then
        echo -e "[+] $ip.$i =>$okegreen PORT 22 OPEN$white"
        echo "$ip.$i" >> openssh.txt
    else
        echo -e "[-] $ip.$i =>$red PORT 22 CLOSED$white"
    fi
done
